---
- name: Verify install directory
  file:
    path: "{{gauss_bin_directory}}/"
    state: directory

- name: Install expect
  yum:
    name: expect
    state: present

- name: Install python3 pip
  yum:
    name: python3-pip
    state: present

- name: Install gdown for remote download
  shell: pip3 install gdown
# pip:
#   name: gdown
#   state: latest

#- name: Install gdown for remote download (SCL)
# become: yes
# become_method: sudo
# shell: |
#   scl enable python27 -- pip install gdown

- name: use gdown to download tar file
  shell: /usr/local/bin/gdown https://drive.google.com/uc?id=1cWMBpd62_-NugCBnJdGjLL6WVy1KRwly -O /tmp/GAUSS_20_Linux_64.tar.gz
#  https://drive.google.com/file/d/1cWMBpd62_-NugCBnJdGjLL6WVy1KRwly/view?usp=sharing
# shell: gdown https://drive.google.com/uc?id=1qaZH9_SrGyjHjWT3P2WtvZAhEkP9YG1Z -O /tmp/ancilRH7_repo.tar.gz
#     when: stage == "DEV_LOCAL"
#       stage values = { "DEV_LOCAL","DEV", "PROD" }



- name: Untar the tarball
  unarchive:
    src: "{{guass_local_bin_directory}}/GAUSS_20_Linux_64.tar.gz"
#   src: "{{guass_local_bin_directory}}/GAUSS_15_Linux_RHEL_64.tar.gz"
    dest: "{{gauss_bin_directory}}/"
  when: custom_repo

- name: copy the expect script
  template:
    src: install_gauss.exp
    dest: "{{gauss_bin_directory}}/install_gauss.exp"
    mode: a+rx

- name: Run gauss expect script
  shell: "./install_gauss.exp"
  args:
    chdir: "{{gauss_bin_directory}}"
  when: custom_repo
